// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDusV0oXl8KEgIH8FCGimhEE4ZyXD_EE',
    appId: '1:662379451779:web:402f1e3bb437a02514d2b6',
    messagingSenderId: '662379451779',
    projectId: 'quizmaker-74d9c',
    authDomain: 'quizmaker-74d9c.firebaseapp.com',
    storageBucket: 'quizmaker-74d9c.appspot.com',
    measurementId: 'G-GHYVYNZEEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi67zGKD5mipztdZpl0D2HLe4c5KtnKME',
    appId: '1:662379451779:android:7558bbb2c923581c14d2b6',
    messagingSenderId: '662379451779',
    projectId: 'quizmaker-74d9c',
    storageBucket: 'quizmaker-74d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpwMejl7_8UfQ4GX-NcoldxE_V5uB1BA',
    appId: '1:662379451779:ios:52e2550c1f95964814d2b6',
    messagingSenderId: '662379451779',
    projectId: 'quizmaker-74d9c',
    storageBucket: 'quizmaker-74d9c.appspot.com',
    iosBundleId: 'com.example.quizmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZpwMejl7_8UfQ4GX-NcoldxE_V5uB1BA',
    appId: '1:662379451779:ios:07d492e9c77d9b9914d2b6',
    messagingSenderId: '662379451779',
    projectId: 'quizmaker-74d9c',
    storageBucket: 'quizmaker-74d9c.appspot.com',
    iosBundleId: 'com.example.quizmaker.RunnerTests',
  );
}
